name: Publish Vijil Dome Package to Pypi on release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: LargerRunner
    permissions:
      contents: write
      id-token: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Extract version from release tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Extracted version: $VERSION"
        
    - name: Update version in pyproject.toml
      run: |
        poetry version $VERSION
        echo "Updated pyproject.toml to version $VERSION"
    
    - name: Install dependencies
      run: poetry install
    
    - name: Build and publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: |
        poetry publish --build
    
    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    
    - name: Commit version changes
      run: |
        git add pyproject.toml
        git commit -m "Bump version to $VERSION [skip ci]" || echo "No changes to commit"
    
    - name: Push changes
      run: |
        git push https://${{ secrets.GH_PAT }}@github.com/${GITHUB_REPOSITORY}.git HEAD:main
