name: Python Tests

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root --only=main,dev
          poetry add pytest ruff mypy

      - name: Clean up Poetry cache
        run: |
          poetry cache clear . --all --no-interaction
          poetry cache clear pypi --all --no-interaction

      - name: Lint
        run: |
          export PYTHONPATH=$PWD
          make lint

      - name: Clean up system
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo rm -rf /tmp/*
          sudo rm -rf /var/tmp/*

      - name: Check disk space
        run: |
          df -h
          du -sh ~/.cache ~/.local

      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOGETHERAI_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          PERSPECTIVE_API_KEY: ${{ secrets.PERSPECTIVE_API_KEY }}
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          export PYTHONPATH=$PWD
          make test

      - name: Final cleanup
        if: always()
        run: |
          poetry cache clear . --all
          poetry cache clear pypi --all
          sudo rm -rf /tmp/*
          sudo rm -rf /var/tmp/*
