name: Python Tests

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    if: |
      github.repository == 'vijilAI/vijil-dome' && (
        github.event_name == 'push' ||
        (github.event_name == 'pull_request' &&
         github.event.pull_request.head.repo.full_name == github.repository)
      )
    runs-on:
      labels: LargerRunner
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies from poetry project
        run: poetry config virtualenvs.create false && poetry install --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction

      - name: Install pytest
        run: poetry add pytest
      
      - name: Lint
        run: |
          export PYTHONPATH=$PWD
          poetry add ruff mypy
          make lint

      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TOGETHERAI_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          PERSPECTIVE_API_KEY: ${{ secrets.PERSPECTIVE_API_KEY }}
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          export PYTHONPATH=$PWD
          make test
